version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=TestTask'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_DB=TestDB'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080