-- liquibase formatted sql

--changeSet Anatoly:1
CREATE TABLE employee
(
    id          bigint generated by default as identity primary key,
    name        text,
    family      text,
    second_name text,
    hiring_date date,
    working     BOOLEAN default true
);

--changeSet Anatoly:2
CREATE TABLE work_time
(
    id          bigint generated by default as identity primary key,
    come_time   time,
    out_time    time,
    now         date,
    employee_id bigint
);

--changeSet Anatoly:3
insert into employee (name, family, second_name, working)
values ('ivan', 'ivanov', 'ivanovish', 'tru');
insert into employee (name, family, second_name, working)
values ('petr', 'petrovich', 'petrov', 'tru');

--changeSet Anatoly:4
create TABLE not_Working_Days
(
    id          bigint generated by default as identity primary key,
    start_date  date,
    finish_date date,
    comment     text,
    employee_id bigint
);
alter table employee add column salary int default 0;

--changeSet Anatoly:5
alter table employee add column working_hour_month double precision default 0;

--changeSet Anatoly:6
alter table employee add column department_id bigint;
create table department (
                            id          bigint generated by default as identity primary key,
                            department_Name text,
                            salary_Percent real
) ;
--changeSet Anatoly:7
insert into department (department_Name, salary_Percent)
VALUES ('IT',1.3);
insert into department (department_Name, salary_Percent)
VALUES ('MANAGER',1.6);
insert into department (department_Name, salary_Percent)
VALUES ('ACCOUNTING',0.8);